# Generated by Django 6.0.3 on 2026-03-29 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_attendancesession_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.batch'),
            preserve_default=False,
        ),
    ]
