# Generated by Django 6.0.3 on 2026-03-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentexamattempt_studentanswer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentexamattempt',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='score',
        ),
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='student',
        ),
    ]
