# Generated by Django 6.0.3 on 2026-04-13 04:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentexamattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentexamattempt',
            options={'ordering': ['-score']},
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentexamattempt',
            unique_together={('student', 'exam')},
        ),
    ]
