# Generated by Django 6.0.3 on 2026-07-22 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_studentexamattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batches',
            field=models.ManyToManyField(blank=True, help_text='Student can belong to multiple batches.', related_name='students', to='students.batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_students', to='students.batch'),
        ),
    ]
