# Generated by Django 6.0.3 on 2026-07-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_batches_alter_student_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='estimated_time',
            field=models.PositiveIntegerField(default=60, help_text='Estimated time in seconds'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_mode',
            field=models.CharField(choices=[('IMAGE', 'Import Question'), ('TYPED', 'Typed Question'), ('HYBRID', 'Hybrid Question')], default='IMAGE', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('SELF', 'Self Created'), ('NCERT', 'NCERT'), ('EXEMPLAR', 'NCERT Exemplar'), ('PYQ', 'Previous Year Question'), ('BOOK', 'Reference Book'), ('AI', 'AI Generated')], default='SELF', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
