# Generated by Django 6.0.3 on 2026-07-27 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_question_difficulty_question_estimated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='students.batch', verbose_name='Batch'),
            preserve_default=False,
        ),
    ]
