# Generated by Django 6.0.3 on 2026-07-28 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_question_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='students.batch'),
        ),
    ]
