# Generated by Django 6.0.3 on 2026-08-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_question_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batches',
        ),
        migrations.AddField(
            model_name='student',
            name='additional_batches',
            field=models.ManyToManyField(blank=True, help_text='Select additional batches. Main Batch is selected above.', related_name='additional_students', to='students.batch', verbose_name='Additional Batches'),
        ),
    ]
