# Generated by Django 6.0.3 on 2026-08-16 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_assessmentsubject_chapters_assessmentsubject_topic'),
        ('students', '0014_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assessment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_exam', to='performance.assessment'),
        ),
    ]
