# Generated by Django 6.0.3 on 2026-08-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_exam_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('MATCH', 'Match the Matrix'), ('CASE', 'Case Study'), ('NUMERICAL', 'Numerical'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer'), ('ASSERTION', 'Assertion–Reason'), ('OTHER', 'Other')], default='MCQ', max_length=15),
        ),
    ]
