# Generated by Django 6.0.3 on 2026-08-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10),
        ),
    ]
