# Generated by Django 6.0.3 on 2026-09-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_repair_exam_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Instructions for this test. These will appear on the test paper PDF.'),
        ),
    ]
