# Generated by Django 6.0.3 on 2026-07-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='assessmentsubject',
            name='chapter_name',
        ),
        migrations.RemoveField(
            model_name='assessmentsubject',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='assessmentsubject',
            name='passing_marks',
        ),
        migrations.RemoveField(
            model_name='assessmentsubject',
            name='weightage',
        ),
        migrations.AddField(
            model_name='assessment',
            name='academic_session',
            field=models.CharField(default=1999, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentsubject',
            name='chapter_covered',
            field=models.CharField(default='2026-27', max_length=250, verbose_name='Chapter Covered'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY_FOR_MARKS', 'Ready for Marks Entry'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmentsubject',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Duration (Minutes)'),
        ),
    ]
