# Generated by Django 6.0.3 on 2026-07-17 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_remove_assessment_remarks_and_more'),
        ('students', '0007_alter_studentexamattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='academic_session',
            field=models.CharField(choices=[('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28'), ('2028-29', '2028-29'), ('2029-30', '2029-30')], max_length=20),
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_scored', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_absent', models.BooleanField(default=False, verbose_name='Absent')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('assessment_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='performance.assessmentsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_marks', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Mark',
                'verbose_name_plural': 'Student Marks',
                'ordering': ['student__student_name'],
                'unique_together': {('assessment_subject', 'student')},
            },
        ),
    ]
