# Generated by Django 6.0.3 on 2026-08-16 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_alter_assessment_academic_session_studentmark'),
        ('students', '0014_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubject',
            name='chapters',
            field=models.ManyToManyField(blank=True, related_name='assessment_chapters', to='students.chapter'),
        ),
        migrations.AddField(
            model_name='assessmentsubject',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_subjects', to='students.topic'),
        ),
    ]
