# Generated by Django 6.0.3 on 2026-08-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_assessmentsubject_chapters_assessmentsubject_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='is_retest',
            field=models.BooleanField(default=False, verbose_name='Retest'),
        ),
    ]
