# Generated by Django 6.0.3 on 2026-08-25 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_studentmark_is_retest'),
        ('students', '0021_repair_exam_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksheetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(max_length=50, verbose_name='Class')),
                ('chapter_name', models.CharField(max_length=200, verbose_name='Chapter Name')),
                ('title', models.CharField(max_length=250, verbose_name='Worksheet Project Title')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ANALYSING', 'Analysing Sources'), ('READY', 'Ready to Generate'), ('GENERATING', 'Generating Worksheets'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('number_of_sets', models.PositiveIntegerField(default=1, verbose_name='Number of Worksheet Sets')),
                ('worksheets_per_set', models.PositiveIntegerField(default=4, verbose_name='Worksheets Per Set')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worksheet_projects', to='students.chapter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheet_projects', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worksheet_projects', to='students.subject')),
            ],
            options={
                'verbose_name': 'Worksheet Project',
                'verbose_name_plural': 'Worksheet Projects',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='WorksheetSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_sets', to='performance.worksheetproject')),
            ],
            options={
                'verbose_name': 'Worksheet Set',
                'verbose_name_plural': 'Worksheet Sets',
                'ordering': ['set_number'],
                'unique_together': {('project', 'set_number')},
            },
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worksheet_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=250)),
                ('worksheet_type', models.CharField(choices=[('FOUNDATION', 'Foundation'), ('CONCEPTUAL', 'Conceptual'), ('APPLICATION', 'Application'), ('HOTS', 'HOTS / Comprehensive'), ('MIXED', 'Mixed')], default='MIXED', max_length=20)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('answer_space_mode', models.CharField(choices=[('AUTO', 'Automatic'), ('COMPACT', 'Compact'), ('STANDARD', 'Standard'), ('SPACIOUS', 'Spacious')], default='AUTO', max_length=20)),
                ('include_answer_key', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to='performance.worksheetset')),
            ],
            options={
                'verbose_name': 'Worksheet',
                'verbose_name_plural': 'Worksheets',
                'ordering': ['worksheet_number'],
                'unique_together': {('set', 'worksheet_number')},
            },
        ),
        migrations.CreateModel(
            name='WorksheetSourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('source_type', models.CharField(choices=[('TEXTBOOK', 'Textbook'), ('NOTES', 'School Notes'), ('REFERENCE', 'Reference Material'), ('PYQ', 'Previous Year Questions'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('pdf_file', models.FileField(upload_to='worksheet_sources/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='performance.worksheetproject')),
            ],
            options={
                'verbose_name': 'Worksheet Source Document',
                'verbose_name_plural': 'Worksheet Source Documents',
                'ordering': ['uploaded_on'],
            },
        ),
        migrations.CreateModel(
            name='WorksheetQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('2M', '2 Marker'), ('3M', '3 Marker'), ('5M', '5 Marker'), ('CASE', 'Case Study')], max_length=10)),
                ('question_number', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField(default=1)),
                ('answer_space_lines', models.PositiveIntegerField(default=3)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worksheet_usages', to='students.question')),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='performance.worksheet')),
            ],
            options={
                'verbose_name': 'Worksheet Question',
                'verbose_name_plural': 'Worksheet Questions',
                'ordering': ['question_number'],
                'unique_together': {('worksheet', 'question_number')},
            },
        ),
    ]
