# Generated by Django 6.0.3 on 2026-09-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_worksheetproject_worksheetset_worksheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('READY_FOR_MARKS', 'Ready for Marks Entry'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20),
        ),
    ]
