# Generated by Django 6.0.3 on 2026-09-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
